# Generated by Django 3.1.7 on 2021-09-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_profile', to='network.Profile'),
        ),
    ]
